
// This file has been generated by the GUI designer. Do not modify.
namespace PinDominator
{
	public partial class frmAddAccounts
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.HButtonBox hbuttonbox1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Entry txtInputUserName;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Entry txtInputPassword;
		
		private global::Gtk.Button btnClearAccounts;
		
		private global::Gtk.Button btnAddAccounts;
		
		private global::Gtk.Entry txtInputProxy;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Entry txtInputNiche;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PinDominator.frmAddAccounts
			this.WidthRequest = 425;
			this.Name = "PinDominator.frmAddAccounts";
			this.Title = global::Mono.Unix.Catalog.GetString ("Add Accounts");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			// Container child PinDominator.frmAddAccounts.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.WidthRequest = 420;
			this.fixed1.HeightRequest = 250;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString (" ");
			this.fixed1.Add (this.label5);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
			w1.X = 67;
			w1.Y = 169;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.fixed1.Add (this.hbuttonbox1);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.hbuttonbox1]));
			w2.X = 64;
			w2.Y = 240;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Email  : ");
			this.fixed1.Add (this.label2);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
			w3.X = 49;
			w3.Y = 45;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtInputUserName = new global::Gtk.Entry ();
			this.txtInputUserName.WidthRequest = 200;
			this.txtInputUserName.CanFocus = true;
			this.txtInputUserName.Name = "txtInputUserName";
			this.txtInputUserName.IsEditable = true;
			this.txtInputUserName.InvisibleChar = '●';
			this.fixed1.Add (this.txtInputUserName);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtInputUserName]));
			w4.X = 139;
			w4.Y = 39;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Password  : ");
			this.fixed1.Add (this.label3);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
			w5.X = 28;
			w5.Y = 85;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtInputPassword = new global::Gtk.Entry ();
			this.txtInputPassword.WidthRequest = 200;
			this.txtInputPassword.CanFocus = true;
			this.txtInputPassword.Name = "txtInputPassword";
			this.txtInputPassword.IsEditable = true;
			this.txtInputPassword.InvisibleChar = '●';
			this.fixed1.Add (this.txtInputPassword);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtInputPassword]));
			w6.X = 139;
			w6.Y = 81;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnClearAccounts = new global::Gtk.Button ();
			this.btnClearAccounts.CanFocus = true;
			this.btnClearAccounts.Name = "btnClearAccounts";
			this.btnClearAccounts.UseUnderline = true;
			this.btnClearAccounts.Label = global::Mono.Unix.Catalog.GetString ("Clear Account ");
			this.fixed1.Add (this.btnClearAccounts);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnClearAccounts]));
			w7.X = 251;
			w7.Y = 204;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnAddAccounts = new global::Gtk.Button ();
			this.btnAddAccounts.CanFocus = true;
			this.btnAddAccounts.Name = "btnAddAccounts";
			this.btnAddAccounts.UseUnderline = true;
			this.btnAddAccounts.Label = global::Mono.Unix.Catalog.GetString ("Add Account ");
			this.fixed1.Add (this.btnAddAccounts);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnAddAccounts]));
			w8.X = 140;
			w8.Y = 204;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtInputProxy = new global::Gtk.Entry ();
			global::Gtk.Tooltips w9 = new Gtk.Tooltips ();
			w9.SetTip (this.txtInputProxy, "Formate -> ProxyIp   : ProxyPort   : ProxyUserName  :  ProxyPassword", "Formate -> ProxyIp   : ProxyPort   : ProxyUserName  :  ProxyPassword");
			this.txtInputProxy.WidthRequest = 200;
			this.txtInputProxy.CanFocus = true;
			this.txtInputProxy.Name = "txtInputProxy";
			this.txtInputProxy.IsEditable = true;
			this.txtInputProxy.InvisibleChar = '●';
			this.fixed1.Add (this.txtInputProxy);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtInputProxy]));
			w10.X = 140;
			w10.Y = 159;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Proxy  : ");
			this.fixed1.Add (this.label4);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
			w11.X = 49;
			w11.Y = 163;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Niche :");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w12.X = 50;
			w12.Y = 126;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtInputNiche = new global::Gtk.Entry ();
			this.txtInputNiche.WidthRequest = 200;
			this.txtInputNiche.CanFocus = true;
			this.txtInputNiche.Name = "txtInputNiche";
			this.txtInputNiche.IsEditable = true;
			this.txtInputNiche.InvisibleChar = '●';
			this.fixed1.Add (this.txtInputNiche);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtInputNiche]));
			w13.X = 139;
			w13.Y = 119;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 425;
			this.DefaultHeight = 321;
			this.Show ();
			this.btnClearAccounts.Clicked += new global::System.EventHandler (this.OnBtnClearAccountsClicked);
			this.btnAddAccounts.Clicked += new global::System.EventHandler (this.OnBtnAddAccountsClicked);
		}
	}
}
