
// This file has been generated by the GUI designer. Do not modify.
namespace PinDominator
{
	public partial class frmUploadUnFollowList
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Frame frameUploadUnFollowList;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Entry txtUnFollowList_UnFollow;
		
		private global::Gtk.Button btnUnFollowlstBrowse_UnFollow;
		
		private global::Gtk.Button btnSaveUnFollowList;
		
		private global::Gtk.Label GtkLabel1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PinDominator.frmUploadUnFollowList
			this.WidthRequest = 500;
			this.HeightRequest = 200;
			this.Name = "PinDominator.frmUploadUnFollowList";
			this.Title = global::Mono.Unix.Catalog.GetString ("frmUploadUnFollowList");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			// Container child PinDominator.frmUploadUnFollowList.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.frameUploadUnFollowList = new global::Gtk.Frame ();
			this.frameUploadUnFollowList.WidthRequest = 490;
			this.frameUploadUnFollowList.HeightRequest = 190;
			this.frameUploadUnFollowList.Name = "frameUploadUnFollowList";
			this.frameUploadUnFollowList.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frameUploadUnFollowList.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("UnFollow List :");
			this.fixed2.Add (this.label2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label2]));
			w1.X = 20;
			w1.Y = 70;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtUnFollowList_UnFollow = new global::Gtk.Entry ();
			this.txtUnFollowList_UnFollow.WidthRequest = 200;
			this.txtUnFollowList_UnFollow.Sensitive = false;
			this.txtUnFollowList_UnFollow.CanFocus = true;
			this.txtUnFollowList_UnFollow.Name = "txtUnFollowList_UnFollow";
			this.txtUnFollowList_UnFollow.IsEditable = true;
			this.txtUnFollowList_UnFollow.InvisibleChar = '●';
			this.fixed2.Add (this.txtUnFollowList_UnFollow);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.txtUnFollowList_UnFollow]));
			w2.X = 115;
			w2.Y = 65;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnUnFollowlstBrowse_UnFollow = new global::Gtk.Button ();
			this.btnUnFollowlstBrowse_UnFollow.WidthRequest = 100;
			this.btnUnFollowlstBrowse_UnFollow.HeightRequest = 27;
			this.btnUnFollowlstBrowse_UnFollow.CanFocus = true;
			this.btnUnFollowlstBrowse_UnFollow.Name = "btnUnFollowlstBrowse_UnFollow";
			this.btnUnFollowlstBrowse_UnFollow.UseUnderline = true;
			this.btnUnFollowlstBrowse_UnFollow.Label = global::Mono.Unix.Catalog.GetString ("  Browse  ");
			this.fixed2.Add (this.btnUnFollowlstBrowse_UnFollow);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.btnUnFollowlstBrowse_UnFollow]));
			w3.X = 340;
			w3.Y = 65;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnSaveUnFollowList = new global::Gtk.Button ();
			this.btnSaveUnFollowList.WidthRequest = 100;
			this.btnSaveUnFollowList.HeightRequest = 27;
			this.btnSaveUnFollowList.CanFocus = true;
			this.btnSaveUnFollowList.Name = "btnSaveUnFollowList";
			this.btnSaveUnFollowList.UseUnderline = true;
			this.btnSaveUnFollowList.Label = global::Mono.Unix.Catalog.GetString ("  Save  ");
			this.fixed2.Add (this.btnSaveUnFollowList);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.btnSaveUnFollowList]));
			w4.X = 340;
			w4.Y = 128;
			this.GtkAlignment.Add (this.fixed2);
			this.frameUploadUnFollowList.Add (this.GtkAlignment);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Upload UnFollow List</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frameUploadUnFollowList.LabelWidget = this.GtkLabel1;
			this.fixed1.Add (this.frameUploadUnFollowList);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.frameUploadUnFollowList]));
			w7.X = 5;
			w7.Y = 5;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 543;
			this.DefaultHeight = 309;
			this.Show ();
			this.btnUnFollowlstBrowse_UnFollow.Clicked += new global::System.EventHandler (this.OnBtnUnFollowlstBrowseUnFollowClicked);
			this.btnSaveUnFollowList.Clicked += new global::System.EventHandler (this.OnBtnSaveUnFollowListClicked);
		}
	}
}
