
// This file has been generated by the GUI designer. Do not modify.
namespace PinDominator
{
	public partial class frmLicensing
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Label lblMacID;
		
		private global::Gtk.Label lblUser;
		
		private global::Gtk.Entry txtUserName;
		
		private global::Gtk.Label lblPasswword;
		
		private global::Gtk.Entry txtPassword;
		
		private global::Gtk.Label lblTransactionID;
		
		private global::Gtk.Label lblEmail;
		
		private global::Gtk.Label lblLicenseType;
		
		private global::Gtk.Label lblLicenseStatus;
		
		private global::Gtk.Entry txtTransactionID;
		
		private global::Gtk.Entry txtEmail;
		
		private global::Gtk.Label lblstatus;
		
		private global::Gtk.Button btnActivate;
		
		private global::Gtk.Button btnStart;
		
		private global::Gtk.ComboBoxEntry cmb_LicType;
		
		private global::Gtk.Label GtkLabel1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PinDominator.frmLicensing
			this.WidthRequest = 600;
			this.HeightRequest = 500;
			this.Name = "PinDominator.frmLicensing";
			this.Title = global::Mono.Unix.Catalog.GetString ("Licensing of PinDominator 3.0");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			// Container child PinDominator.frmLicensing.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.WidthRequest = 520;
			this.frame1.HeightRequest = 420;
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblMacID = new global::Gtk.Label ();
			this.lblMacID.Name = "lblMacID";
			this.lblMacID.LabelProp = global::Mono.Unix.Catalog.GetString ("MAC-ID :");
			this.fixed2.Add (this.lblMacID);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lblMacID]));
			w1.X = 160;
			w1.Y = 17;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblUser = new global::Gtk.Label ();
			this.lblUser.Name = "lblUser";
			this.lblUser.LabelProp = global::Mono.Unix.Catalog.GetString ("       Username :");
			this.fixed2.Add (this.lblUser);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lblUser]));
			w2.X = 80;
			w2.Y = 60;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtUserName = new global::Gtk.Entry ();
			this.txtUserName.WidthRequest = 170;
			this.txtUserName.CanFocus = true;
			this.txtUserName.Name = "txtUserName";
			this.txtUserName.IsEditable = true;
			this.txtUserName.InvisibleChar = '●';
			this.fixed2.Add (this.txtUserName);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.txtUserName]));
			w3.X = 220;
			w3.Y = 55;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblPasswword = new global::Gtk.Label ();
			this.lblPasswword.Name = "lblPasswword";
			this.lblPasswword.LabelProp = global::Mono.Unix.Catalog.GetString ("        Password :");
			this.fixed2.Add (this.lblPasswword);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lblPasswword]));
			w4.X = 80;
			w4.Y = 110;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtPassword = new global::Gtk.Entry ();
			this.txtPassword.WidthRequest = 170;
			this.txtPassword.CanFocus = true;
			this.txtPassword.Name = "txtPassword";
			this.txtPassword.IsEditable = true;
			this.txtPassword.InvisibleChar = '●';
			this.fixed2.Add (this.txtPassword);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.txtPassword]));
			w5.X = 220;
			w5.Y = 103;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblTransactionID = new global::Gtk.Label ();
			this.lblTransactionID.Name = "lblTransactionID";
			this.lblTransactionID.LabelProp = global::Mono.Unix.Catalog.GetString ("Transcation Id :");
			this.fixed2.Add (this.lblTransactionID);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lblTransactionID]));
			w6.X = 80;
			w6.Y = 155;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblEmail = new global::Gtk.Label ();
			this.lblEmail.Name = "lblEmail";
			this.lblEmail.LabelProp = global::Mono.Unix.Catalog.GetString ("               Email :");
			this.fixed2.Add (this.lblEmail);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lblEmail]));
			w7.X = 80;
			w7.Y = 200;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblLicenseType = new global::Gtk.Label ();
			this.lblLicenseType.Name = "lblLicenseType";
			this.lblLicenseType.LabelProp = global::Mono.Unix.Catalog.GetString ("  License Type : ");
			this.fixed2.Add (this.lblLicenseType);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lblLicenseType]));
			w8.X = 80;
			w8.Y = 245;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblLicenseStatus = new global::Gtk.Label ();
			this.lblLicenseStatus.Name = "lblLicenseStatus";
			this.lblLicenseStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("License Status :");
			this.fixed2.Add (this.lblLicenseStatus);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lblLicenseStatus]));
			w9.X = 80;
			w9.Y = 297;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtTransactionID = new global::Gtk.Entry ();
			this.txtTransactionID.WidthRequest = 170;
			this.txtTransactionID.CanFocus = true;
			this.txtTransactionID.Name = "txtTransactionID";
			this.txtTransactionID.IsEditable = true;
			this.txtTransactionID.InvisibleChar = '●';
			this.fixed2.Add (this.txtTransactionID);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.txtTransactionID]));
			w10.X = 220;
			w10.Y = 146;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtEmail = new global::Gtk.Entry ();
			this.txtEmail.WidthRequest = 170;
			this.txtEmail.CanFocus = true;
			this.txtEmail.Name = "txtEmail";
			this.txtEmail.IsEditable = true;
			this.txtEmail.InvisibleChar = '●';
			this.fixed2.Add (this.txtEmail);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.txtEmail]));
			w11.X = 220;
			w11.Y = 196;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblstatus = new global::Gtk.Label ();
			this.lblstatus.Name = "lblstatus";
			this.lblstatus.LabelProp = global::Mono.Unix.Catalog.GetString (" Status");
			this.fixed2.Add (this.lblstatus);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lblstatus]));
			w12.X = 220;
			w12.Y = 297;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnActivate = new global::Gtk.Button ();
			this.btnActivate.WidthRequest = 0;
			this.btnActivate.CanFocus = true;
			this.btnActivate.Name = "btnActivate";
			this.btnActivate.UseUnderline = true;
			this.btnActivate.Label = global::Mono.Unix.Catalog.GetString (" Activate");
			this.fixed2.Add (this.btnActivate);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.btnActivate]));
			w13.X = 220;
			w13.Y = 350;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnStart = new global::Gtk.Button ();
			this.btnStart.HeightRequest = 28;
			this.btnStart.CanFocus = true;
			this.btnStart.Name = "btnStart";
			this.btnStart.UseUnderline = true;
			this.btnStart.Label = global::Mono.Unix.Catalog.GetString ("Start PinDominator");
			this.fixed2.Add (this.btnStart);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.btnStart]));
			w14.X = 220;
			w14.Y = 350;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.cmb_LicType = global::Gtk.ComboBoxEntry.NewText ();
			this.cmb_LicType.WidthRequest = 163;
			this.cmb_LicType.HeightRequest = 25;
			this.cmb_LicType.Name = "cmb_LicType";
			this.fixed2.Add (this.cmb_LicType);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.cmb_LicType]));
			w15.X = 226;
			w15.Y = 242;
			this.GtkAlignment.Add (this.fixed2);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b></b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel1;
			this.fixed1.Add (this.frame1);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.frame1]));
			w18.X = 35;
			w18.Y = 20;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 757;
			this.DefaultHeight = 600;
			this.Show ();
			this.btnStart.Clicked += new global::System.EventHandler (this.OnBtnStartClicked);
		}
	}
}
